#+TITLE: Notes on AI seminary
#+AUTHOR: Sil Vaes

* MIND: Turing
https://phil415.pbworks.com/f/TuringComputing.pdf
https://www.csee.umbc.edu/courses/471/papers/turing.pdf

-> Gepubliceerd in MIND: Psychology and Philosophy -> Turing was buiten CS geinteresseerd in filosofie (philosophy of mind?) -> Kijk naar hard question of consciousness (kort bespreken)

De centrale vraag is: ‘Can machines think?’, wat is de definitie van "machine" en "think"? Kan met een survey opgelost worden -> reframing.

Gebruik "the imitation game" -> er zijn drie personen: A is een man, B een vrouw en C de ondervrager. C moet bepalen wie de vrouw en man is. A moet proberen de ondervrager tegen te werken en B moet de ondervrager helpen. Stel dat een computer de rol van A overneemt, kan deze de rol even goed overnemen als een echt persoon? Dit vervangt de vraag "Can machines think?".

Fysieke en intellectuelen delen van de machine/persoon zijn gescheiden. Men moet geen machine maken die lijkt op een mens, enkel die kan antwoorden als een mens. Veel menselijke ondernemingen kunnen geintroduceerd worden; schaken, wiskunde, poezie, kunst etc. En de machine kan deze ook ontwijken (kan een machine kunst maken? Iets uniek produceren?).

De theorie van het spel moet niet onderzocht worden, enkel het imiteren van een mens.

Wat is de machine in deze context? Alles dat door mensen gemaakt is, niet enkel AI (dit is wel het eerste waar we aan denken als we menselijke intelligentie willen beschrijven). Niet iets clonen van gemaakt van menslijke cellen, dit is een mens. Turing zegt: het moet een "electronic computer" zijn.

Verder legt Turing ook uit hoe een "Digital Computer" werkt, hoeft niet uitgelegd te worden in het seminarie. Wel interessant is een computer met random element, heeft het dan "free will"? Dan zou het echt random moeten zijn, niet pseudorandom.

"Digital Computers" kunnen gezien worden als een discrete state machine. Van een initial state en de input signalen kunnen alle komende states voorspeld worden. Zoals Laplace's visie op het universum: als je alle variabelen van de state van het universum op een tijdstip hebt, kan je alles voorspellen (posities en snelheden van de deeltjes). Maar dit is niet praktisch, want fouten in de initial variables kunnen grote gevolgen hebben miljoenen jaren later bijvoorbeeld: een elektron die verkeerd is kan een mens doden.

Een computer als discrete state machine heeft wel enorm veel states. Computers kunnen state machines nabootsen -> universal machines.

Nu dus: ‘Are there imaginable digital computers which would do well in the imitation game?’ -> algemener: ‘Are there discrete state machines which would do well?’.

** Contrary views:

Eerst Turing's kijk: Hij denkt dat binnen 50 jaar machines dit kunnen doen met 70% success rate (gepubliceerd in 1950, dus in 2000 -> niet helemaal waar). "Can machines think?" is volgens hem een nutteloze vraag -> Turing was een aanhanger van het logisch positivisme: verwerpt de non-empirische uitspraken die worden gedaan in de metafysica, de theologie en de ethiek -> denken kan niet empirisch worden vastgesteld (positivisme: alleen de empirische wetenschappen leveren geldige kennis op).

- Theologische objecties: Denken is een functie van de zien van de mens etc. (Rare interpretatie van hem, ook fout mbt Copernicaanse revolutie/Galileo).
- Heads in the Sand: Machines die denken is te eng. De mens is superieur aan alles.
- Wiskundige objectie: Discrete state machines zijn te beperkt (nu al wat minder relevant). Is de menselijke capaciteit ook niet beperkt? Hebben wij niet de illusie dat wij onbeperkt zijn omdat we niet "buiten onszelf" kunnen denken? Wij kunnen ons bewustzijn toch ook niet beschrijven -> gelimiteerd. Wel kunnen we aan metacognitie doen.
- Argument from Consciousness: “Not until a machine can write a sonnet or compose a concerto because of thoughts and emotions felt, and not by the chance fall of symbols, could we agree that machine equals brain—that is, not only write it but know that it had written it. No mechanism could feel (and not merely artificially signal, an easy contrivance) pleasure at its successes, grief when its valves fuse, be warmed by flattery, be made miserable by its mistakes, be charmed by sex, be angry or depressed when it cannot get what it wants.” Is een beetje een solipsisme. Met kan enkel weten of een machine denkt door een machine te zijn en als een te denken. Ook, men kan enkel zeker zijn dat iemand denkt door die iemand te zijn en hem te voelen denken.
- From Various Disabilities: Machines zullen altijd een handicap hebben. Ze kunnen de Imitation Game halen, maar nooit X. Machines zullen nooit van eten kunnen genieten als ons, of kunst beschouwen etc. Deze zijn niet echt relevant om de ondervrager te overtuigen, de machine moet deze enkel kunnen imiteren. Ze missen bepaalde menselijke karakteristieken.
- Lady Lovelace's Objection: The Analytical Engine has no pretensions to originate anything. It can do whatever we know how to order it to perform”. Een machine kan dus niets uniek doen, enkel wat wij het opdragen. Hartree: “This does not imply that it may not be possible to construct electronic equipment which will ‘think for itself’, or in which, in biological terms, one could set up a conditioned reflex, which would serve as a basis for ‘learning’. Whether this is possible in principle or not is a stimulating and exciting question, suggested by some of these recent developments. But it did not seem that the machines constructed or projected at the time had this property”.
- Argument from Continuity in the Nervous System: Een zenuwstelsel is niet discreet, een kleine fout kan grote fouten hebben in dit continue systeem. Dus een machine kan dit niet nabootsen. -> Een machine kan dit nabootsen (A differential analyser).
- The Argument from Informality of Behaviour: Het is niet mogelijk om alle gedragingen van een persoon bij te houden. Knowledge bases?
- The Argument from Extra-Sensory Perception: ?? Schizo talk ??

Turing zegt dat voordat een learning machine mogelijk is meer engineering nodig is, in 1950 was volgens hem het grootste probleem het programmeren van de machine.

State van het brein om het te immiteren?

- The initial state of the mind, say at birth,

- The education to which it has been subjected,

- Other experience, not to be described as education, to which it has been subjected.

Beetje zoals machine learning: eerst heeft men een kinderbrein, daarna moet men het dingen aanleren. -> probleem opgedeeld in twee delen: het maken van een kinderbrein en de education.

Verschillende technieken:
- Survival of the fittest.
- Punishment and reward (reinforcement learning).

Wat is een "child machine"? Algemene principes? Logical inference (definitions and propositions)? 

"An important feature of a learning machine is that its teacher will often be very largely ignorant of quite what is going on inside, although he may still be able to some extent to predict his pupil's behaviour." -> Opaque process.


* Passes Turing test posing as teenager?
http://www.sci-news.com/othersciences/computerscience/science-eugene-goostman-supercomputer-program-turing-test-01978.html

https://www.techdirt.com/articles/20140609/07284327524/no-supercomputer-did-not-pass-turing-test-first-time-everyone-should-know-better.shtml

https://www.kurzweilai.net/mt-notes-on-the-announcement-of-chatbot-eugene-goostman-passing-the-turing-test

"This "bot" is completely different from what Turing envisioned. When he referred to the 30% of judges fooled, he was thinking of a machine that was using MACHINE LEARNING, and a lot of storage, and hence was able to store patterns and information that it received over time and make coherent responses based on that information. However these "bots" just have a pattern matching algorithm that matches for content and then resolves a pre-defined response. Also the REAL turing test is not about "fooling 30% of people", it's about a computer being INDISTINGUISHABLE from a human in the game of imitation. Look up indistinguishability in computer science if you want to know the specifics of what it means in mathmatical terms."

"being given the age or country of origin in order to forgive any weirdnesses just seems a bit like cheating."

-> Dit zijn vooral chatbots -> niet wat Turing in gedachte had
